### PR TITLE
Update Link to Open Data Census

### LINKED ISSUE #43: update link to Open Data Census
on http://www.opencleveland.org/opendatacensus/

the new link to the census is http://us-cities.survey.okfn.org/

### PR DESCRIPTION
**Pull request by danielhelfand**
Closes #43 

Updating the [Open Data Census page](http://www.opencleveland.org/opendatacensus/) of opencleveland.org to point to the [new census link](http://us-cities.survey.okfn.org/).

### CODE REVIEW

**Comment by danielhelfand** [comment]
Was curious if the second link in the text should be updated to http://us-cities.survey.okfn.org/place/cleveland as well.

**Comment by skorasaurus** [comment]
hey, thanks! 

If you want to update the second link as well, that'd be super too!

**Comment by danielhelfand** [comment]
@skorasaurus Sure thing! Glad to help.

**Comment by skorasaurus** [comment]
Thank you again. :)

**Pull request merged**
